Examen1/Examen1/Models/ErrorViewModel.cs
using System;

namespace Examen1.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Examen1/Examen1/Models/Paciente.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Examen1.Models
{
    public class Paciente
    {
        [Key]
        public int PacienteId { get; set; }

        [Display(Name = "Nombre")]
        [Required(ErrorMessage = "El nombre es obligatorio")]
        [RegularExpression("^[a-zA-Z ]*$", ErrorMessage = "Solo ingrese letras")]
        public string PacienteNombre { get; set; }

        [Required(ErrorMessage = "El segundo nombre es obligatorio")]
        [Display(Name = "Segundo Nombre")]
        [RegularExpression("^[a-zA-Z ]*$", ErrorMessage = "Solo ingrese letras")]
        public string PacienteSegundoNombre { get; set; }

        [Required(ErrorMessage = "Los Apellidos son obligatorios")]
        [Display(Name = "Apellidos")]
        [RegularExpression("^[a-zA-Z ]*$", ErrorMessage = "Solo ingrese letras")]
        public string PacienteApellido { get; set; }

        [Required(ErrorMessage = "El correo es obligatorio")]
        [Display(Name = "Correo")]
        [DataType(DataType.EmailAddress)]
        public string PacienteCorreo { get; set; }

        [Display(Name = "Nombre Acompañante")]
        [RegularExpression("^[a-zA-Z ]*$", ErrorMessage = "Solo ingrese letras")]
        public string PacienteAcompañanteNombre { get; set; }

        [Display(Name = "Apellido Acompañante")]
        [RegularExpression("^[a-zA-Z ]*$", ErrorMessage = "Solo ingrese letras")]
        public string PacienteAcompañanteApellido { get; set; }

        [Required(ErrorMessage = "Direccion de calle es obligatoria")]
        [Display(Name = "Direccion Calle")]
        public string PacienteDireccionCalle { get; set; }

        [Display(Name = "Direccion Calle Linea 2")]
        public string PacienteDireccionCalleLinea2 { get; set; }

        [Display(Name = "Ciudad")]
        [RegularExpression("^[a-zA-Z ]*$", ErrorMessage = "Solo ingrese letras")]
        public string PacienteCiudad { get; set; }

        [Display(Name = "Provincia")]
        [RegularExpression("^[a-zA-Z ]*$", ErrorMessage = "Solo ingrese letras")]
        public string PacienteProvincia { get; set; }

        [Display(Name = "Postal")]
        [RegularExpression("(^[0-9]+$)", ErrorMessage = "Solo se permiten números")]
        public string PacienteCodigoPostal { get; set; }

        [Display(Name = "CodTelefono")]
        [Required(ErrorMessage = "Codigo de area obligatorio")]
        [RegularExpression("(^[0-9]+$)", ErrorMessage = "Solo se permiten números")]
        public string PacienteCodigoAreaTelefono { get; set; }

        [Display(Name = "Telefono")]
        [Required(ErrorMessage = "Telefono es obligatorio")]
        [RegularExpression("(^[0-9]+$)", ErrorMessage = "Solo se permiten números")]
        public string PacienteNumeroTelefono { get; set; }

        [Display(Name = "CodCelular")]
        [RegularExpression("(^[0-9]+$)", ErrorMessage = "Solo se permiten números")]
        public string PacienteCodigoAreaCelular { get; set; }

        [Display(Name = "Celular")]
        [RegularExpression("(^[0-9]+$)", ErrorMessage = "Solo se permiten números")]
        public string PacienteNumeroCelular { get; set; }
    }
}

Examen1/Examen1/Controllers/HomeController.cs
using Examen1.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Examen1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Examen1/Examen1/Controllers/PacientesController.cs
using Examen1.Data;
using Examen1.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Examen1.Controllers
{
    public class PacientesController : Controller
    {
        private readonly ApplicationDbContext db;

        public PacientesController(ApplicationDbContext db)
        {
            this.db = db;
        }

        public async Task<IActionResult> Index(string search) 
        {
            if (search == null)
            {
                return View(await db.Pacientes.ToListAsync());
            }
            return View(await db.Pacientes
                .Where(p => p.PacienteNombre.Contains(search))
                .ToListAsync());
        }

        public async Task<IActionResult> Details(int? id) 
        {
            if (id == null)
            {
                return NotFound();
            }

            var paciente = await db.Pacientes.FirstOrDefaultAsync(p => p.PacienteId == id);

            if (paciente == null)
            {
                return NotFound();
            }

            return View(paciente);
        }

        public IActionResult Create() 
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Paciente paciente) 
        {
            if (ModelState.IsValid)
            {
                db.Add(paciente);
                await db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(paciente);
        }

        public async Task<IActionResult> Edit(int? id) 
        {
            if (id==null)
            {
                return NotFound();
            }

            var paciente = await db.Pacientes.FindAsync(id);

            if (paciente == null)
            {
                return NotFound();
            }

            return View(paciente);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Paciente paciente) 
        {
            if (id != paciente.PacienteId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    db.Update(paciente);
                    await db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    return NotFound();
                }

                return RedirectToAction(nameof(Index));
            }

            return View(paciente);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var paciente = await db.Pacientes.FirstOrDefaultAsync(p => p.PacienteId == id);

            if (paciente == null)
            {
                return NotFound();
            }

            return View(paciente);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var paciente = await db.Pacientes.FindAsync(id);
            db.Pacientes.Remove(paciente);
            await db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Examen1/Examen1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Examen1/Examen1/Views/Pacientes/Create.cshtml
@model Examen1.Models.Paciente

@{
    ViewData["Title"] = "Ingresar Paciente";
}

<h2 class="text-light">Ingreso de Paciente</h2>

<div class="row">
    <div class="col-12">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group text-light input-group">
                <div class="col-2 small"><label> Nombres y Apellidos <br /> del paciente</label></div>
                <div class="col-3 small">
                    <input asp-for="PacienteNombre" class="form-control small textbox" />
                    <span asp-validation-for="PacienteNombre" class="text-danger"></span>
                    <label> Nombre </label>
                </div>
                <div class="col-3 small">
                    <input asp-for="PacienteSegundoNombre" class="form-control small textbox" />
                    <span asp-validation-for="PacienteSegundoNombre" class="text-danger"></span>
                    <label> Segundo Nombre </label>
                </div>
                <div class="col-4 small">
                    <input asp-for="PacienteApellido" class="form-control small textbox" />
                    <span asp-validation-for="PacienteApellido" class="text-danger"></span>
                    <Label> Apellidos </Label>
                </div>
                <div class="col-2 small"><label> Correo <br /> Electronico </label></div>
                <div class="col-7 small">
                    <input asp-for="PacienteCorreo" class="form-control small textbox" />
                    <span asp-validation-for="PacienteCorreo" class="text-danger"></span>
                    <Label> example@example.com </Label>
                </div>
                <div class="col-3 small"></div>
                <div class="col-2 small">
                    <label>Nombre del <br />Acompañante</label>
                </div>
                <div class="col-3 small">
                    <input asp-for="PacienteAcompañanteNombre" class="form-control small textbox" />
                    <span asp-validation-for="PacienteAcompañanteNombre" class="text-danger"></span>
                    <Label> Nombre </Label>
                </div>
                <div class="col-3 small">
                    <input asp-for="PacienteAcompañanteApellido" class="form-control small textbox" />
                    <span asp-validation-for="PacienteAcompañanteApellido" class="text-danger"></span>
                    <Label> Apellido </Label>
                </div>
                <div class="col-4 small"></div>
                <div class="col-2 small">
                    <label>Direccion</label>
                </div>
                <div class="col-10 small">
                    <input asp-for="PacienteDireccionCalle" class="form-control textbox col-7" />
                    <span asp-validation-for="PacienteDireccionCalle" class="text-danger"></span>
                    <Label> Direccion de la calle </Label>
                </div>
                <div class="col-2 small">
                </div>
                <div class="col-10 small">
                    <input asp-for="PacienteDireccionCalleLinea2" class="form-control textbox col-7" />
                    <span asp-validation-for="PacienteDireccionCalleLinea2" class="text-danger"></span>
                    <Label> Direccion de la calle linea 2 </Label>
                </div>

                <div class="col-2 small"></div>
                <div class="col-3 small">
                    <input asp-for="PacienteCiudad" class="form-control small textbox " />
                    <span asp-validation-for="PacienteCiudad" class="text-danger"></span>
                    <label> Ciudad </label>
                </div>
                <div class="col-3 small">
                    <input asp-for="PacienteProvincia" class="form-control small textbox " />
                    <span asp-validation-for="PacienteProvincia" class="text-danger"></span>
                    <label> Estado/Provincia </label>
                </div>
                <div class="col-4 small"></div>
                <div class="col-2 small"></div>
                <div class="col-3 small">
                    <input asp-for="PacienteCodigoPostal" class="form-control small textbox " />
                    <span asp-validation-for="PacienteCodigoPostal" class="text-danger"></span>
                    <label> Codigo Postal </label>
                </div>
                <div class="col-7 small"></div>
                <div class="col-2 small"><label>Numero de Telefono</label></div>
                <div class="col-1 small">
                    <input asp-for="PacienteCodigoAreaTelefono" class="form-control small textbox " />
                    <span asp-validation-for="PacienteCodigoAreaTelefono" class="text-danger"></span>
                    <label> Codigo de Area </label>
                </div>
                <div class="col-3 small">
                    <input asp-for="PacienteNumeroTelefono" class="form-control small textbox " />
                    <span asp-validation-for="PacienteNumeroTelefono    " class="text-danger"></span>
                    <label> Numero de telefono </label>
                </div>
                <div class="col-6 small"></div>
                <div class="col-2 small"><label>Numero de Whatsapp</label></div>
                <div class="col-1 small">
                    <input asp-for="PacienteCodigoAreaCelular" class="form-control small textbox " />
                    <span asp-validation-for="PacienteCodigoAreaCelular" class="text-danger"></span>
                    <label> Codigo de Area </label>
                </div>
                <div class="col-3 small">
                    <input asp-for="PacienteNumeroCelular" class="form-control small textbox " />
                    <span asp-validation-for="PacienteNumeroCelular" class="text-danger"></span>
                    <label> Numero de Celular </label>
                </div>
                <div class="col-6"></div>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-outline-light" />
                <a asp-action="Index" class="btn btn-outline-light"><i class="fas fa-undo-alt"></i> Regresar</a>
            </div>
        </form>
    </div>
</div>

<link rel="stylesheet" href="~/css/custom.css" />
@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Examen1/Examen1/Views/Pacientes/Delete.cshtml
@model Examen1.Models.Paciente

@{
    ViewData["Title"] = "Borrar Paciente";
}

<h2 class="text-light">Borrar Paciente</h2>
<h3 class="text-light">¿Esta seguro que desea eliminar el registro?</h3>

<div>
    <hr />
    <dl class="row text-light">
        <dd class="col-2 borde boldo" style="">
            @Html.DisplayNameFor(model => model.PacienteNombre)
        </dd>
        <dd class="col-2 borde">
            @Html.DisplayFor(model => model.PacienteNombre)
        </dd>
        <dd class="col-2 borde boldo">
            @Html.DisplayNameFor(model => model.PacienteSegundoNombre)
        </dd>
        <dd class="col-2 borde">
            @Html.DisplayFor(model => model.PacienteSegundoNombre)
        </dd>
        <dd class="col-2 borde boldo">
            @Html.DisplayNameFor(model => model.PacienteApellido)
        </dd>
        <dd class="col-2 borde">
            @Html.DisplayFor(model => model.PacienteApellido)
        </dd>
        <dd class="col-2 borde boldo">
            @Html.DisplayNameFor(model => model.PacienteCorreo)
        </dd>
        <dd class="col-10 borde">
            @Html.DisplayFor(model => model.PacienteCorreo)
        </dd>
        <dd class="col-2 borde boldo small">
            @Html.DisplayNameFor(model => model.PacienteAcompañanteNombre)
        </dd>
        <dd class="col-2 borde">
            @Html.DisplayFor(model => model.PacienteAcompañanteNombre)
        </dd>
        <dd class="col-2 borde boldo small">
            @Html.DisplayNameFor(model => model.PacienteAcompañanteApellido)
        </dd>
        <dd class="col-2 borde">
            @Html.DisplayFor(model => model.PacienteAcompañanteApellido)
        </dd>
        <dd class="col-2 borde"></dd>
        <dd class="col-2 borde"></dd>
        <dd class="col-2 borde boldo">
            @Html.DisplayNameFor(model => model.PacienteDireccionCalle)
        </dd>
        <dd class="col-10 borde">
            @Html.DisplayFor(model => model.PacienteDireccionCalle)
        </dd>
        <dd class="col-2 borde boldo small">
            @Html.DisplayNameFor(model => model.PacienteDireccionCalleLinea2)
        </dd>
        <dd class="col-10 borde">
            @Html.DisplayFor(model => model.PacienteDireccionCalleLinea2)
        </dd>
        <dd class="col-2 borde boldo">
            @Html.DisplayNameFor(model => model.PacienteCiudad)
        </dd>
        <dd class="col-2 borde">
            @Html.DisplayFor(model => model.PacienteCiudad)
        </dd>
        <dd class="col-2 borde boldo">
            @Html.DisplayNameFor(model => model.PacienteProvincia)
        </dd>
        <dd class="col-2 borde">
            @Html.DisplayFor(model => model.PacienteProvincia)
        </dd>
        <dd class="col-2 borde"></dd>
        <dd class="col-2 borde"></dd>
        <dd class="col-2 borde boldo">
            @Html.DisplayNameFor(model => model.PacienteCodigoAreaTelefono)
        </dd>
        <dd class="col-2 borde">
            @Html.DisplayFor(model => model.PacienteCodigoAreaTelefono)
        </dd>
        <dd class="col-2 borde boldo">
            @Html.DisplayNameFor(model => model.PacienteNumeroTelefono)
        </dd>
        <dd class="col-2 borde">
            @Html.DisplayFor(model => model.PacienteNumeroTelefono)
        </dd>
        <dd class="col-2 borde"></dd>
        <dd class="col-2 borde"></dd>
        <dd class="col-2 borde boldo">
            @Html.DisplayNameFor(model => model.PacienteCodigoAreaCelular)
        </dd>
        <dd class="col-2 borde">
            @Html.DisplayFor(model => model.PacienteCodigoAreaCelular)
        </dd>
        <dd class="col-2 borde boldo">
            @Html.DisplayNameFor(model => model.PacienteNumeroCelular)
        </dd>
        <dd class="col-2 borde">
            @Html.DisplayFor(model => model.PacienteNumeroCelular)
        </dd>
        <dd class="col-4 borde"></dd>
    </dl>
</div>

<div>
    <form asp-action="Delete">
        <input type="hidden" asp-for="PacienteId" />
        <input type="submit" class="btn btn-outline-light" value="Borrar" />
        <a asp-action="Index" class="btn btn-outline-light"><i class="fas fa-undo-alt"></i> Regresar</a>
    </form>
</div>
<link rel="stylesheet" href="~/css/custom.css" />

Examen1/Examen1/Views/Pacientes/Details.cshtml
@model Examen1.Models.Paciente

@{
    ViewData["Title"] = "Detalles Paciente";
}

<h2 class="text-light">Detalles Paciente</h2>

<div>
    <hr />
    <dl class="row text-light">
        <dd class="col-2 borde boldo" style="">
            @Html.DisplayNameFor(model => model.PacienteNombre)
        </dd>
        <dd class="col-2 borde">
            @Html.DisplayFor(model => model.PacienteNombre)
        </dd>
        <dd class="col-2 borde boldo">
            @Html.DisplayNameFor(model => model.PacienteSegundoNombre)
        </dd>
        <dd class="col-2 borde">
            @Html.DisplayFor(model => model.PacienteSegundoNombre)
        </dd>
        <dd class="col-2 borde boldo">
            @Html.DisplayNameFor(model => model.PacienteApellido)
        </dd>
        <dd class="col-2 borde">
            @Html.DisplayFor(model => model.PacienteApellido)
        </dd>
        <dd class="col-2 borde boldo">
            @Html.DisplayNameFor(model => model.PacienteCorreo)
        </dd>
        <dd class="col-10 borde">
            @Html.DisplayFor(model => model.PacienteCorreo)
        </dd>
        <dd class="col-2 borde boldo small">
            @Html.DisplayNameFor(model => model.PacienteAcompañanteNombre)
        </dd>
        <dd class="col-2 borde">
            @Html.DisplayFor(model => model.PacienteAcompañanteNombre)
        </dd>
        <dd class="col-2 borde boldo small">
            @Html.DisplayNameFor(model => model.PacienteAcompañanteApellido)
        </dd>
        <dd class="col-2 borde">
            @Html.DisplayFor(model => model.PacienteAcompañanteApellido)
        </dd>
        <dd class="col-2 borde"></dd>
        <dd class="col-2 borde"></dd>
        <dd class="col-2 borde boldo">
            @Html.DisplayNameFor(model => model.PacienteDireccionCalle)
        </dd>
        <dd class="col-10 borde">
            @Html.DisplayFor(model => model.PacienteDireccionCalle)
        </dd>
        <dd class="col-2 borde boldo small">
            @Html.DisplayNameFor(model => model.PacienteDireccionCalleLinea2)
        </dd>
        <dd class="col-10 borde">
            @Html.DisplayFor(model => model.PacienteDireccionCalleLinea2)
        </dd>
        <dd class="col-2 borde boldo">
            @Html.DisplayNameFor(model => model.PacienteCiudad)
        </dd>
        <dd class="col-2 borde">
            @Html.DisplayFor(model => model.PacienteCiudad)
        </dd> 
        <dd class="col-2 borde boldo">
            @Html.DisplayNameFor(model => model.PacienteProvincia)
        </dd>
        <dd class="col-2 borde">
            @Html.DisplayFor(model => model.PacienteProvincia)
        </dd>
        <dd class="col-2 borde"></dd>
        <dd class="col-2 borde"></dd>
        <dd class="col-2 borde boldo">
            @Html.DisplayNameFor(model => model.PacienteCodigoAreaTelefono)
        </dd>
        <dd class="col-2 borde">
            @Html.DisplayFor(model => model.PacienteCodigoAreaTelefono)
        </dd>
        <dd class="col-2 borde boldo">
            @Html.DisplayNameFor(model => model.PacienteNumeroTelefono)
        </dd>
        <dd class="col-2 borde">
            @Html.DisplayFor(model => model.PacienteNumeroTelefono)
        </dd>
        <dd class="col-2 borde"></dd>
        <dd class="col-2 borde"></dd>
        <dd class="col-2 borde boldo">
            @Html.DisplayNameFor(model => model.PacienteCodigoAreaCelular)
        </dd>
        <dd class="col-2 borde">
            @Html.DisplayFor(model => model.PacienteCodigoAreaCelular)
        </dd>
        <dd class="col-2 borde boldo">
            @Html.DisplayNameFor(model => model.PacienteNumeroCelular)
        </dd>
        <dd class="col-2 borde">
            @Html.DisplayFor(model => model.PacienteNumeroCelular)
        </dd>
        <dd class="col-4 borde"></dd>
    </dl>
</div>

<div>
    <a asp-action="Edit" class="btn btn-outline-light" asp-route-id="@Model.PacienteId"><i class="fas fa-edit"></i> Editar</a>
    <a asp-action="Index" class="btn btn-outline-light"><i class="fas fa-undo-alt"></i> Regresar</a>
</div>
<link rel="stylesheet" href="~/css/custom.css" />

Examen1/Examen1/Views/Pacientes/Index.cshtml
@model IEnumerable<Examen1.Models.Paciente>

@{
    ViewData["Title"] = "Citas";
}

<h2 class="text-light">Citas</h2>

<div class="row search">
    <div class="col-auto">
        <input type="text" class="form-control-plaintext small text-light" id="txt-search" placeholder="Buscar..." style="margin-bottom: 10px;"/>
    </div>
    <div class="col-auto">
        <a class="btn btn-outline-light btn-sm text-light" onclick="pacientes_search()" id="search-link" style="margin-bottom: 10px;"><i class="fas fa-search-plus"></i> Buscar</a>
        <a asp-action="Create" class="btn btn-outline-light btn-sm" style="margin-bottom: 10px;"><i class="far fa-file"></i> Nuevo</a>
    </div>
</div>
<div>
    <div class="table-responsive">
        <table class="table table-hover">
            <thead class="table-dark">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.PacienteNombre)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PacienteApellido)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PacienteCorreo)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PacienteCiudad)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td class="text-light">@Html.DisplayFor(modelItem => item.PacienteNombre)</td>
                        <td class="text-light">@Html.DisplayFor(modelItem => item.PacienteApellido)</td>
                        <td class="text-light">@Html.DisplayFor(modelItem => item.PacienteCorreo)</td>
                        <td class="text-light">@Html.DisplayFor(modelItem => item.PacienteCiudad)</td>
                        <td>
                            <a asp-action="Edit" class="btn btn-outline-light" asp-route-id="@item.PacienteId"><i class="fas fa-edit"></i> Editar</a>
                            <a asp-action="Details" class="btn btn-outline-light" asp-route-id="@item.PacienteId"><i class="fas fa-file"></i> Detalles</a>
                            <a asp-action="Delete" class="btn btn-outline-light" asp-route-id="@item.PacienteId"><i class="fas fa-trash"></i> Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<script src="~/js/pacientes.js" asp-append-version="true"></script>

Examen1/Examen1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Examen1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
</head>
<body class="bg-dark">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Examen1</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pacientes" asp-action="Index">Pacientes</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Examen1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>